name: Upload Model from CivitAI to Hugging Face

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  upload-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests huggingface_hub

      - name: Download model from CivitAI
        run: |
          MODEL_ID="YOUR_MODEL_ID" # Replace with your CivitAI model ID
          CIVITAI_TOKEN="${{ secrets.CIVITAI_TOKEN }}"
          DOWNLOAD_URL="https://civitai.com/api/download/models/$MODEL_ID?token=$CIVITAI_TOKEN"

          # Download the model
          curl -L -o model.zip "$DOWNLOAD_URL"
          echo "Model downloaded successfully!"

      - name: Upload model to Hugging Face
        run: |
          python upload_to_huggingface.py --model_path model.zip --repo_id ${{ secrets.HF_REPO_ID }} --token ${{ secrets.HF_TOKEN }}
